version: "3.8"

services: 
  server:
    # image: 'nginx:1.24.0-alpine'
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
      # `.` referes to current folder where `.yaml` is there.
      # We need to copy `src` folder to `WORKDIR` inside docker
      # So If we we mention `context: ./dockerfiles`, Parent folder for this service won't be in the same directory of `src`
    ports: 
      - '8000:80'
    volumes: 
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
  mysql:
    image: mysql:8.2.0
    env_file:
      - ./env/mysql.env
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
  artisan:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]
  npm:
    image: node:20.10.0
    working_dir: /var/www/html
    entrypoint: ["npm"]
    volumes:
      - ./src:/var/www/html
